pipeline {
    agent any

    tools {
        nodejs "NodeJS"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/ToniBommisetty/ToniWholeSale.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo 'No tests defined yet'
            }
        }

        stage('Deploy') {
            steps {
                bat 'echo Starting application...'
                bat 'start /B node server.js'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful'
        }
        failure {
            echo 'Deployment Failed'
        }
    }
}