pipeline {
    agent any

    tools {
        nodejs "NodeJS"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                url: 'https://github.com/ToniBommisetty/ToniWholeSale.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }

        stage('Stop Existing Server') {
            steps {
                bat '''
                FOR /F "tokens=5" %%P IN ('netstat -ano ^| findstr :3000') DO taskkill /PID %%P /F || exit 0
                '''
            }
        }

        stage('Start Server') {
            steps {
                bat 'start /B node server.js'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful (Node without PM2)'
        }
    }
}